"""empty message

Revision ID: 893b0de529d9
Revises: a4788316e847
Create Date: 2024-06-04 20:51:12.484194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893b0de529d9'
down_revision = 'a4788316e847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')

    # ### end Alembic commands ###
